
import "./globals.css";
import Navbar from "@/Components/Navbar";
import Footer from "@/Components/Footer";
import SessionWrapper from "@/Components/SessionWrapper";

export const metadata = {
  title: "InstaFam",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={` antialiased`} >
        <SessionWrapper>  
          <Navbar />
          {children}
          <Footer />
        </SessionWrapper> 
      </body>
    </html>
  );
}
