
import "./globals.css";
// import "../styles/globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import SessionWrapper from "@/components/SessionWrapper";
import { Analytics } from "@vercel/analytics/next"
import { ThemeProvider } from "@/context/ThemeContext";

export const metadata = {
  title: "InstaFam",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={` antialiased`} >
        <SessionWrapper>  
          <ThemeProvider>
            <Navbar />
            {children}
            <Footer />
          </ThemeProvider>
          <Analytics/>
        </SessionWrapper> 
      </body>
    </html>
  );
}
